require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BillsController do

  # This should return the minimal set of attributes required to create a valid
  # Bill. As you add validations to Bill, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "amount" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BillsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all bills as @bills" do
      bill = Bill.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bills).should eq([bill])
    end
  end

  describe "GET show" do
    it "assigns the requested bill as @bill" do
      bill = Bill.create! valid_attributes
      get :show, {:id => bill.to_param}, valid_session
      assigns(:bill).should eq(bill)
    end
  end

  describe "GET new" do
    it "assigns a new bill as @bill" do
      get :new, {}, valid_session
      assigns(:bill).should be_a_new(Bill)
    end
  end

  describe "GET edit" do
    it "assigns the requested bill as @bill" do
      bill = Bill.create! valid_attributes
      get :edit, {:id => bill.to_param}, valid_session
      assigns(:bill).should eq(bill)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bill" do
        expect {
          post :create, {:bill => valid_attributes}, valid_session
        }.to change(Bill, :count).by(1)
      end

      it "assigns a newly created bill as @bill" do
        post :create, {:bill => valid_attributes}, valid_session
        assigns(:bill).should be_a(Bill)
        assigns(:bill).should be_persisted
      end

      it "redirects to the created bill" do
        post :create, {:bill => valid_attributes}, valid_session
        response.should redirect_to(Bill.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bill as @bill" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bill.any_instance.stub(:save).and_return(false)
        post :create, {:bill => { "amount" => "invalid value" }}, valid_session
        assigns(:bill).should be_a_new(Bill)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bill.any_instance.stub(:save).and_return(false)
        post :create, {:bill => { "amount" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end

    context "with meta" do
      it "creates a new Bill with given JSON" do
        post :create, {bill: {amount: 100, meta: {test: 'hello'}.to_json}}, valid_session

        expect(Bill.last.meta['test']).to eq 'hello'
      end
    end
  end

  describe "PUT update" do
    let!(:bill) { Bill.create! valid_attributes }
    describe "with valid params" do
      it "updates the requested bill" do
        expect {
          put :update, {:id => bill.to_param, :bill => { "amount" => "10" }}, valid_session
        }.to change {
          bill.reload.amount
        }.from(1).to(10)
      end

      it "assigns the requested bill as @bill" do
        put :update, {:id => bill.to_param, :bill => valid_attributes}, valid_session
        assigns(:bill).should eq(bill)
      end

      it "redirects to the bill" do
        put :update, {:id => bill.to_param, :bill => valid_attributes}, valid_session
        response.should redirect_to(bill)
      end
    end

    describe "with invalid params" do
      it "assigns the bill as @bill" do
        Bill.any_instance.stub(:save).and_return(false)
        put :update, {:id => bill.to_param, :bill => { "amount" => "invalid value" }}, valid_session
        assigns(:bill).should eq(bill)
      end

      it "re-renders the 'edit' template" do
        Bill.any_instance.stub(:save).and_return(false)
        put :update, {:id => bill.to_param, :bill => { "amount" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end

    context "with meta" do
      it "creates a new Bill with given JSON" do
        put :update, {id: bill.to_param, bill: {meta: {test: 'hello'}.to_json}}, valid_session

        expect(bill.reload.meta['test']).to eq 'hello'
      end

      context "without meta" do
        before do
          bill.meta['hello'] = 'hola'
          bill.save!
        end

        it "lets meta as is" do
        put :update, {id: bill.to_param, bill: {amount: 10}}, valid_session
          expect(bill.reload.meta['hello']).to eq 'hola'
        end
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bill" do
      bill = Bill.create! valid_attributes
      expect {
        delete :destroy, {:id => bill.to_param}, valid_session
      }.to change(Bill, :count).by(-1)
    end

    it "redirects to the bills list" do
      bill = Bill.create! valid_attributes
      delete :destroy, {:id => bill.to_param}, valid_session
      response.should redirect_to(bills_url)
    end
  end

end
